const express = require("express");
var localStorage = require("localStorage");
const app = express();
app.use(express.json());
const CustomerDetails=require("./api/routes/CustomerDetails");
const otp = require("./api/routes/otp");
const InsertBasicInfo = require("./models/mysql/CustomerDetailsSchema");
localStorage.setItem("count", 1);
app.use("/otp", otp);
app.use("/CustomerDetails", CustomerDetails);
module.exports = app;
